wandb inited <wandb.sdk.wandb_run.Run object at 0x7feac3b08650> {}
Files already downloaded and verified
/opt/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:3829: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
Batch 0
{'std_loss': tensor(0.3993), 'std_acc': tensor(0.8672), 'adv_loss': tensor(2.0373), 'adv_acc': tensor(0.3828)}
Batch 1
{'std_loss': tensor(0.4207), 'std_acc': tensor(0.8477), 'adv_loss': tensor(2.1590), 'adv_acc': tensor(0.3516)}
Batch 2
{'std_loss': tensor(0.4224), 'std_acc': tensor(0.8516), 'adv_loss': tensor(2.1107), 'adv_acc': tensor(0.3854)}
Batch 3
{'std_loss': tensor(0.3783), 'std_acc': tensor(0.8691), 'adv_loss': tensor(2.0440), 'adv_acc': tensor(0.3965)}
Batch 4
{'std_loss': tensor(0.3728), 'std_acc': tensor(0.8687), 'adv_loss': tensor(1.9993), 'adv_acc': tensor(0.4109)}
Batch 5
{'std_loss': tensor(0.4031), 'std_acc': tensor(0.8620), 'adv_loss': tensor(2.0371), 'adv_acc': tensor(0.4154)}
Batch 6
{'std_loss': tensor(0.3981), 'std_acc': tensor(0.8650), 'adv_loss': tensor(2.0539), 'adv_acc': tensor(0.4185)}

Aborted!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1127, in emit
    StreamHandler.emit(self, record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 2034, in shutdown
    h.close()
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1103, in close
