wandb inited <wandb.sdk.wandb_run.Run object at 0x7f3ee9402850> {}
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 308, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/eval.py", line 134, in <module>
    main()
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "examples/eval.py", line 131, in main
    run(**flags)
  File "examples/eval.py", line 56, in run
    ckpt = torch.load(FLAGS.ckpt_path)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 235, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 220, in __init__
    _check_seekable(buffer)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 311, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 304, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
