wandb inited <wandb.sdk.wandb_run.Run object at 0x7f9305dc0750> {}
Files already downloaded and verified
/opt/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:3829: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
Batch 0
{'std_loss': tensor(0.6260), 'std_acc': tensor(0.7891), 'adv_loss': tensor(1.1637), 'adv_acc': tensor(0.6250)}
Batch 1
{'std_loss': tensor(0.6476), 'std_acc': tensor(0.7891), 'adv_loss': tensor(1.2508), 'adv_acc': tensor(0.5664)}
Batch 2
{'std_loss': tensor(0.6798), 'std_acc': tensor(0.7708), 'adv_loss': tensor(1.3097), 'adv_acc': tensor(0.5599)}
Batch 3
{'std_loss': tensor(0.6435), 'std_acc': tensor(0.7773), 'adv_loss': tensor(1.2537), 'adv_acc': tensor(0.5684)}
Batch 4
{'std_loss': tensor(0.6188), 'std_acc': tensor(0.7891), 'adv_loss': tensor(1.2278), 'adv_acc': tensor(0.5797)}
Batch 5
{'std_loss': tensor(0.6582), 'std_acc': tensor(0.7760), 'adv_loss': tensor(1.2691), 'adv_acc': tensor(0.5742)}
Batch 6
{'std_loss': tensor(0.6637), 'std_acc': tensor(0.7746), 'adv_loss': tensor(1.2949), 'adv_acc': tensor(0.5681)}

Aborted!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1127, in emit
    StreamHandler.emit(self, record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 2034, in shutdown
    h.close()