wandb inited <wandb.sdk.wandb_run.Run object at 0x7fa84dec6750> {}
Files already downloaded and verified
Batch 0
{'std_loss': tensor(0.6260), 'std_acc': tensor(0.7891), 'adv_loss': tensor(11.9336), 'adv_acc': tensor(0.)}
Batch 1
{'std_loss': tensor(0.6476), 'std_acc': tensor(0.7891), 'adv_loss': tensor(11.9399), 'adv_acc': tensor(0.0039)}
Batch 2
{'std_loss': tensor(0.6798), 'std_acc': tensor(0.7708), 'adv_loss': tensor(11.9327), 'adv_acc': tensor(0.0026)}
Batch 3
{'std_loss': tensor(0.6435), 'std_acc': tensor(0.7773), 'adv_loss': tensor(11.9364), 'adv_acc': tensor(0.0020)}
Batch 4
{'std_loss': tensor(0.6188), 'std_acc': tensor(0.7891), 'adv_loss': tensor(11.8815), 'adv_acc': tensor(0.0016)}
Batch 5
{'std_loss': tensor(0.6582), 'std_acc': tensor(0.7760), 'adv_loss': tensor(11.8995), 'adv_acc': tensor(0.0013)}

Aborted!
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1127, in emit
    StreamHandler.emit(self, record)
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 2034, in shutdown
    h.close()
  File "/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1103, in close
